### ISSUE TITLE
Requirement that `readme.txt` is in the `.wordpress-org` Directory is Not the Correct Standard

### ISSUE THREAD

**Issue by timnolte** [semantic-release/wordpress#166]
### Current behavior

I'm not sure if this is a documentation issue or an implementation issue but the requirement that the `readme.txt` needs to be in the `.wordpress-org` directory seems completely wrong as this is not the correct standard. The `readme.txt` file is required to be in the root of the plugin or theme directory.

### Expected behavior

Support `readme.txt` in the repository root as is the general best practice.

### `semantic-release` version

"semantic-release": "^22.0.8", "@semantic-release/wordpress": "^1.5.4"

### CI environment

Buildkite

### Plugins used

- @semantic-release/commit-analyzer
- @semantic-release/release-notes-generator
- @semantic-release/changelog
- @semantic-release/git
- @semantic-release/wordpress

### `semantic-release` configuration

```json
{
	"branches": ["main", "feature/Build-Release-Tooling"],
	"tagFormat": "${version}",
	"plugins": [
		[
			"@semantic-release/commit-analyzer",
			{
				"preset": "conventionalcommits"
			}
		],
		[
			"@semantic-release/release-notes-generator",
			{
				"preset": "conventionalcommits",
			}
		],
		[
			"@semantic-release/changelog",
			{
				"changelogFile": "CHANGELOG.md",
				"changelogTitle": "# Change Log"
			}
		],
		[
			"@semantic-release/git",
			{
				"assets": ["CHANGELOG.md"]
			}
		],
		[
			"@semantic-release/wordpress",
			{
				"type": "theme",
				"slug" : "internal-theme-name",
				"withReadme": true,
				"withVersionFile": true
			}
		]
	],
}
```

### CI logs

Just testing this out locally at the moment and trying to get clarification on the correct configuration.

**Comment by timnolte** [comment]
What I have done for now is basically created a symbolic link from the `.wordpress-org/readme.txt` to the root `readme.txt`.

**Comment by seebeen** [comment]
Hello Tim,

First of all, you are 100% right - readme.txt should be in the rootdir of the plugin. Specifically in the trunk directory. but we're talking on wp.org.

Let me better explain the endgame for this semantic-release plugin:

## Goals
1. Release channel - zip archive **completed**
2. Release channel - private repository (in progress)
3. Release channel - wp.org (planning phase)
4. Readme.txt generation (stage 1) - Using [semantic-release/changelog](/semantic-release/changelog) to automatically fill in the changelog in readme.txt
5. Readme.txt generation (stage 2) - Automatic filling of plugin details from main plugin.php file
6. Readme.txt generation (stage 3) - Automatic filling and parsing of screenshots with their descriptions

readme.txt is in the .wordpress-org directory so it can be separate from the main readme.md file. Look at [Serbian Addons plugin](/oblakstudio/serbian-addons-for-woocommerce).

By keeping the readmes separated, project can have one readme for the source control and another for wp.org or other systems. 

Currently I'm still in the planning stage for the wp.org release channel because of a conversation I've had with @dd32 (which you can view [here](https://wordpress.slack.com/archives/C1LBM36LC/p1692772215887359)).  
This plugin works with both plugins and themes, but the theme release for wp.org is different, So I'm still trying to figure out a one-size fits all solution.

Another thing to "worry" about is the private repository thing. 100 people, 100 types of private wp repositories - so a one-size-fits-all solution is impossible there as well.

All that being said. I can imlement it so that the readme.txt is copied from .wordpress-org to the plugin / theme dir during the prepare stage. Would that work for you?

**Comment by timnolte** [comment]
@seebeen so something that I've been hoping to implement is the automatic conversion of the WP `readme.txt` to a README.md in order to reduce maintenance overhead. My only concern would be challenges with the `readme.txt` living in the .wordpress-org` directory which wouldn't be what such integrations would expect. 🤔 

See: https://www.npmjs.com/package/gulp-readme-to-markdown
See: https://www.npmjs.com/package/grunt-wp-readme

**Comment by timnolte** [comment]
I am very clear on the difference in audiences. However, even the WP.org site, along with details in the `readme.txt` has elements for developers. So to say that they are mutually exclusive is actually not correct. I also don't want to have to maintain 2 readme files, and for GitHub there is already a general practice of using a `CONTRIBUTING.md` file and the Wiki for developer only stuff.

That being said, I'm not asking for this extension to provide the functionality of converting the `readme.txt` to a `README.md` file, I'm requesting that the `readme.txt` be allowed to be in the root of the repo as an alternative instead of requiring it to be in the `.wordpress-org` directory. This also comes into play where a plugin should be installable directly from packagist.org.
